### ISSUE TITLE
Add titles to fav components

### ISSUE THREAD

**Issue by TomHAnderson** [etreedb/trove#10]

**Comment by paulayo93** [comment]
What is about Trove?
Is it an open project or what?

**Comment by TomHAnderson** [comment]
Yes it's open source and this is the repo for it.
The application is at https://trove.etreedb.org but has not been publicly released because the underlying data needs to be refreshed and that process takes a couple days.  When that happens Trove will be broken for a time.  I'm working on ways to reduce that downtime.

Your question really belongs on a new issue.  If you've got further questions along these lines please create a new issue.

**Comment by TomHAnderson** [comment]
Titles have been added.
